name: Changelog contribution
on:
  workflow_dispatch:
    inputs:
      log:
        description: 'Contributed log'
        required: true

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Generate branch id
        id: branch_id
        run: echo "name=id::$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_OUTPUT
      - name: Get current date
        id: current_date
        run: echo "name=date::$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Create file
        run: |
          mkdir -p ./changelog/billing
          echo "test" > ./changelog/billing/test.txt
      - name: Create pull request towards the main branch
        uses: peter-evans/create-pull-request@v4.1.1
        with:
          token: ${{ secrets.PAT }}
          commit-message: Auto Pull Request
          title: New changelog - ${{ steps.current_date.outputs.date }}
          body: Auto-created Pull Request
          branch: changelog/${{ steps.branch_id.outputs.id }}
          delete-branch: true
