name: Changelog contribution
on:
  workflow_dispatch:
    inputs:
      reporter:
        description: 'Reporter (Name and Surname)'
        required: true
      status:
        description: 'Status of the new logs'
        required: true
      description:
        description: 'Description of the new logs'
        required: true

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Generate branch id
        id: branch_id
        run: echo "::set-output name=id::$(date +'%Y-%m-%d-%H%M%S')"
      - name: Get current date
        id: current_date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create file
        run: |
          mkdir -p ./changelog/billing/$(date +'%B%Y')
          cat > ./changelog/billing/$(date +'%B%Y')/${{ steps.current_date.outputs.date }}-${{ 
github.event.inputs.status }}.mdx << EOF
          ---
          title: Lorem ipsum dolor sit amet
          status: ${{ github.event.inputs.status }}
          author: 
              fullname: ${{ github.event.inputs.reporter }}
              url: 'http://www.scaleway.com'
          date: ${{ steps.current_date.outputs.date }}
          category: storage
          product: object-storage
          ---
          ${{ github.event.inputs.description }}
          EOF
      - name: Create pull request towards the main branch
        uses: peter-evans/create-pull-request@v4.1.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: Auto Pull Request
          title: New changelog - ${{ github.event.inputs.reporter }} ${{ 
steps.current_date.outputs.date }}
          body: Auto-created Pull Request
          branch: changelog/${{ github.event.inputs.status }}/${{ steps.branch_id.outputs.id }}
          delete-branch: true
